- work_column:
    work_sheet: "MAPPING 690291"
    work_codice_prestazione_siss: "CODICE PRESTAZIONE SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE PRESTAZIONE SISS"
    work_codice_agenda_siss: "CODICE SISS AGENDA"
    work_casi_1_n: "CASI 1:N"
    work_abilitazione_esposizione_siss: "NEW ABILITAZIONE ESPOSIZIONE SISS"
    work_codici_disciplina_catalogo: "CODICE_DISCIPLINA_X_QD"
    work_descrizione_disciplina_catalogo: "DESCRIZIONE DISCIPLINA AGENDA"
    work_codice_QD: "QUESITO"
    work_descrizione_QD: "DESCRIZIONE QUESITO"
    work_operatore_logico_QD: "OPERATORE LOGICO QUESITO"
    work_codice_metodica: "METODICA,"
    work_descrizione_metodica: "DESCRIZIONE METODICA"
    work_codice_distretto: "DISTRETTO_ANATOMICO"
    work_descrizione_distretto: "DESCRIZIONE_DISTRETTO"
    work_operatore_logico_distretto: "OPER_LOGIC_DISTRETTO"
    work_priorita_U: "NEW PRIORITA' U"
    work_priorita_primo_accesso_D: "NEW PRIORITA'  PRIMO ACCESSO OD"
    work_priorita_primo_accesso_P: "NEW PRIORITA'  PRIMO ACCESSO OP"
    work_priorita_primo_accesso_B: "NEW PRIORITA'  PRIMO ACCESSO OB"
    work_accesso_programmabile_ZP: "NEW PRIORITA'  CONTROLLO ACCESSO PROGRAMMABILE ZP"
    work_combinata: "NEW COMBINATA"
    work_codice_agenda_interno: "CODICE INTERNO AGENDA"
    work_codice_prestazione_interno: "CODICE INTERNO PRESTAZIONE"

- work_index:
    work_index_sheet: 1
    work_index_codice_QD: 95
    work_index_codice_SISS_agenda: 15
    work_index_abilitazione_esposizione_SISS: 29
    work_index_codice_prestazione_SISS: 25
    work_index_operatore_logico_distretto: 106
    work_index_codici_disciplina_catalogo: 94
    work_index_codici_descri_disciplina_catalogo: 11
    work_index_operatore_logico_QD: 97
    work_alert_column: "DJ"

- work_separator:
    work_delimiter: ","