- work_column:
    work_sheet: "Tracciato Mapping"
    work_codice_prestazione_siss: "CODCE_PRESTAZIONE_SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE_PRESTAZIONE_SISS"
    work_codice_agenda_siss: "CODICE_SISS_AGENDA"
    work_casi_1_n: "CASI 1_N"
    work_abilitazione_esposizione_siss: "ABILITAZIONESISS"
    work_codici_disciplina_catalogo: "COD_DISCIPLINA"
    work_descrizione_disciplina_catalogo: "DESCRIZIONE_DISCIPLINA"
    work_codice_QD: "CODICE_QUES"
    work_descrizione_QD: "DESCRIZIONE_QUES"
    work_operatore_logico_QD: "OPERATORE_QUESITO"
    work_codice_metodica: "CODICE_METODICA"
    work_descrizione_metodica: "DESCR_METODICA"
    work_codice_distretto: "CODICE_DISTRETTO"
    work_descrizione_distretto: "DESCR_DISTRETTO"
    work_operatore_logico_distretto: "OPERATORE_LOGICO"
    work_priorita_U: "U"
    work_priorita_primo_accesso_D: "D"
    work_priorita_primo_accesso_P: "P"
    work_priorita_primo_accesso_B: "B"
    work_accesso_programmabile_ZP: "PROGRAMMABILE"
    work_combinata: "COMBINATA"
    work_codice_agenda_interno: "CODICE_INTERNO_AGENDA"
    work_codice_prestazione_interno: "CODICE_PRESTAZIONE_CUP"

- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 33
    work_index_op_logic_distretto: 49
    work_index_codice_SISS_agenda: 16
    work_index_abilitazione_esposizione_SISS: 23
    work_index_codice_prestazione_SISS: 21
    work_index_operatore_logico_distretto: 49
    work_index_codici_disciplina_catalogo: 31
    work_index_codici_descri_disciplina_catalogo: 32
    work_index_operatore_logico_QD: 35
    work_alert_column: "BT"

- work_separator:
    work_delimiter: ","