- work_column:
    work_sheet: "Mapping 03 09 2021"
    work_codice_prestazione_siss: "CODICE PRESTAZIONE SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE PRESTAZIONE SISS"
    work_codice_agenda_siss: "CODICE SISS AGENDA"
    work_casi_1_n: "CASI 1_N"
    work_abilitazione_esposizione_siss: "NEW ABILITAZIONE ESPOSIZIONE SISS"
    work_codici_disciplina_catalogo: "Codice disciplina da catalogo"
    work_descrizione_disciplina_catalogo: "Descrizione disciplina da catalogo"
    work_codice_QD: "Codice Quesito Diagnostico"
    work_descrizione_QD: "Descrizione Quesito Diagnostico"
    work_operatore_logico_QD: "Operatore Logico Quesito Diagnostico"
    work_codice_metodica: "Codice Metodica"
    work_descrizione_metodica: "Descrizione Metodica"
    work_codice_distretto: "Codice Distretto"
    work_descrizione_distretto: "Descrizione Distretto"
    work_operatore_logico_distretto: "Operatore Logico Distretto"
    work_priorita_U: "Priorità U"
    work_priorita_primo_accesso_D: "Priorità Primo Accesso D"
    work_priorita_primo_accesso_P: "Priorità Primo Accesso P"
    work_priorita_primo_accesso_B: "Priorità Primo Accesso B"
    work_accesso_programmabile_ZP: "Accesso Programmabile P"
    work_combinata: "NEW_COMBINATA"
    work_codice_agenda_interno: "CODICE INTERNO AGENDA"
    work_codice_prestazione_interno: "CODICE INTERNO PRESTAZIONE"

- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 46
    work_index_op_logic_distretto: 59
    work_index_codice_SISS_agenda: 16
    work_index_abilitazione_esposizione_SISS: 28
    work_index_codice_prestazione_SISS: 21
    work_index_operatore_logico_distretto: 59
    work_index_codici_disciplina_catalogo: 44
    work_index_operatore_logico_QD: 48
    work_alert_column: "DI"

- work_separator:
    work_delimiter: ","