- work_column:
    work_sheet: "Tracciato Mapping"
    work_codice_prestazione_siss: "CODCE_PRESTAZIONE_SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE_PRESTAZIONE_SISS"
    work_codice_agenda_siss: "CODICE_SISS_AGENDA"
    work_casi_1_n: "CASI 1_N"
    work_abilitazione_esposizione_siss: "ABILITAZIONESISS"
    work_codici_disciplina_catalogo: "COD_DISCIPLINA"
    work_descrizione_disciplina_catalogo: "DESCRIZIONE_DISCIPLINA"
    work_codice_QD: "QD_CODICI"
    work_descrizione_QD: "QD_DESCRIZIONE"
    work_operatore_logico_QD: "OPERATORE_QUESITO"
    work_codice_metodica: "cod_metodiche"
    work_descrizione_metodica: "descr_metodiche"
    work_codice_distretto: "COD_distretti"
    work_descrizione_distretto: "dESC_distretti"
    work_operatore_logico_distretto: "inclusione_distretti"
    work_priorita_U: "priorita_u"
    work_priorita_primo_accesso_D: "priorita_d"
    work_priorita_primo_accesso_P: "priorita_P"
    work_priorita_primo_accesso_B: "priorita_b"
    work_accesso_programmabile_ZP: "PROGRAMMABILE"
    work_combinata: "COMBINATA"
    work_codice_agenda_interno: "CODICE_INTERNO_AGENDA"
    work_codice_prestazione_interno: "CODICE_PRESTAZIONE_CUP"

- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 35
    work_index_op_logic_distretto: 51
    work_index_codice_SISS_agenda: 16
    work_index_abilitazione_esposizione_SISS: 25
    work_index_codice_prestazione_SISS: 21
    work_index_operatore_logico_distretto: 51
    work_index_codici_disciplina_catalogo: 33
    work_index_codici_descri_disciplina_catalogo: 34
    work_index_operatore_logico_QD: 37
    work_alert_column: "BU"

- work_separator:
    work_delimiter: ","