- work_column:
    work_sheet: "controllo distretti"
    work_codice_prestazione_siss: "CODICE PRESTAZIONE SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE PRESTAZIONE SISS"
    work_codice_agenda_siss: "CODICE SISS AGENDA"
    work_casi_1_n: "casi 1:n"
    work_abilitazione_esposizione_siss: "ABILITAZIONESISS"
    work_codici_disciplina_catalogo: "UEDISCIPLINA"
    work_descrizione_disciplina_catalogo: "disciplina"
    work_codice_QD: "QD_CODICI"
    work_descrizione_QD: "QD_DESCRIZIONE"
    work_operatore_logico_QD: "INCLUSIONE_QD"
    work_codice_metodica: "Codice Metodica"
    work_descrizione_metodica: "Descrizione Metodica"
    work_codice_distretto: "Codice Distretto"
    work_descrizione_distretto: "Descrizione Distretto"
    work_operatore_logico_distretto: "INCLUSIONE_DISTRETTI"
    work_priorita_U: "PRIORITA_U"
    work_priorita_primo_accesso_D: "PRIORITA_D"
    work_priorita_primo_accesso_P: "PRIORITA_P"
    work_priorita_primo_accesso_B: "PRIORITA_B"
    work_accesso_programmabile_ZP: "PRIORITA_PP"
    
    
- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 34
    work_index_op_logic_distretto: 47
    work_index_codice_SISS_agenda: 14
    work_index_abilitazione_esposizione_SISS: 24
    work_index_codice_prestazione_SISS: 21
    work_index_operatore_logico_distretto: 47
    work_index_codici_disciplina_catalogo: 11