- work_column:
    work_sheet: "ASST Lecco"
    work_codice_prestazione_siss: "COD_SISS"
    work_descrizione_prestazione_siss: "DESCR_INTERNA_PRESTAZIONE"
    work_codice_agenda_siss: "CODICE_INTERNO_AGENDA"
    work_casi_1_n: "CASI 1_N"
    work_abilitazione_esposizione_siss: "NEW_ABILITAZIONE_ESPOSIZIONE_SISS"
    work_codici_disciplina_catalogo: "DISC_PER_QUESITO_DIAGNOSTICO"
    work_descrizione_disciplina_catalogo: "DISCIPLINA"
    work_codice_QD: "CD_QUESITO_DIAGNOSTICO"
    work_descrizione_QD: "DESC_QUESITO_DIAGNOSTICO"
    work_operatore_logico_QD: "OPER_LOGIC_QUESITO"
    work_codice_metodica: "CD_METODICA"
    work_descrizione_metodica: "DESC_METODICA"
    work_codice_distretto: "CD_DISTRETTO"
    work_descrizione_distretto: "DESC_DISTRETTO"
    work_operatore_logico_distretto: "OPER_LOGIC_DISTRETTO"
    work_priorita_U: "NEW PRIORITA_URGENTE"
    work_priorita_primo_accesso_D: "NEW_PRIORITA_ORDINARIA_OD"
    work_priorita_primo_accesso_P: "NEW_PRIORITA_ORDINARIA_OP"
    work_priorita_primo_accesso_B: "NEW_PRIORITA_B"
    work_accesso_programmabile_ZP: "NEW_PRIORITA_ACCESSO_PROGRAMMABILE ZP"
    work_combinata: "ISTANZE_COMBINATA"
    work_codice_agenda_interno: "CODICE_INTERNO_AGENDA"
    work_codice_prestazione_interno: "CODICE_INTERNO_PRESTAZIONE"

- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 49
    work_index_op_logic_distretto: 57
    work_index_codice_SISS_agenda: 13
    work_index_abilitazione_esposizione_SISS: 31
    work_index_codice_prestazione_SISS: 21
    work_index_operatore_logico_distretto: 57
    work_index_codici_disciplina_catalogo: 48
    work_index_codici_descri_disciplina_catalogo: 12
    work_index_operatore_logico_QD: 51
    work_alert_column: "DB"

- work_separator:
    work_delimiter: ","