- work_column:
    work_sheet: "Sheet 1"
    work_codice_prestazione_siss: "CODICE PRESTAZIONE SISS"
    work_descrizione_prestazione_siss: "DESCRIZIONE PRESTAZIONE SISS"
    work_codice_agenda_siss: "CODICE SISS AGENDA"
    work_casi_1_n: "CASI 1:N"
    work_abilitazione_esposizione_siss: "NEW ABILITAZIONE ESPOSIZIONE SISS"
    work_codici_disciplina_catalogo: "CODICE_DISCIPLINA_X_QD"
    work_descrizione_disciplina_catalogo: "DESCRIZIONE DISCIPLINA AMMINISTRATIVA"
    work_codice_QD: "QUESITO_DIAGNOSTICO"
    work_descrizione_QD: "DESCRIZIONE_QD"
    work_operatore_logico_QD: "OPER_LOGIC_QUESITO"
    work_codice_metodica: "METODICA,"
    work_descrizione_metodica: "DESCRIZIONE METODICA"
    work_codice_distretto: "DISTRETTO"
    work_descrizione_distretto: "DESCRIZIONE DISTRETTO"
    work_operatore_logico_distretto: "OPERATORE LOGICO DISTRETTO"
    work_priorita_U: "NEW PRIORITA' U"
    work_priorita_primo_accesso_D: "NEW PRIORITA'  PRIMO ACCESSO OD"
    work_priorita_primo_accesso_P: "NEW PRIORITA'  PRIMO ACCESSO OP"
    work_priorita_primo_accesso_B: "NEW PRIORITA'  PRIMO ACCESSO OB"
    work_accesso_programmabile_ZP: "NEW PRIORITA'  CONTROLLO ACCESSO PROGRAMMABILE ZP"
    work_combinata: "NEW COMBINATA"
    work_codice_agenda_interno: "CODICE INTERNO AGENDA"
    work_codice_prestazione_interno: "CODICE INTERNO PRESTAZIONE"

- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 46
    work_index_op_logic_distretto: 58
    work_index_codice_SISS_agenda: 15
    work_index_abilitazione_esposizione_SISS: 27
    work_index_codice_prestazione_SISS: 24
    work_index_operatore_logico_distretto: 58
    work_index_codici_disciplina_catalogo: 45
    work_index_codici_descri_disciplina_catalogo: 11
    work_index_operatore_logico_QD: 48
    work_alert_column: "CX"

- work_separator:
    work_delimiter: ","