- work_column:
    work_sheet: "000415 - Cardinal Shuster"
    work_codice_prestazione_siss: "Codice Prestazione SISS"
    work_descrizione_prestazione_siss: "Descrizione Prestazione SISS"
    work_codice_agenda_siss: "Codice Interno Agenda"
    work_casi_1_n: "CASI 1_N"
    work_abilitazione_esposizione_siss: "Abilititazione Esposizione SISS"
    work_codici_disciplina_catalogo: "Disciplina Agenda"
    work_descrizione_disciplina_catalogo: "Descrizione disciplina da catalogo"
    work_codice_QD: "Codice Quesito Diagnostico"
    work_descrizione_QD: "Descrizione Quesito Diagnostico"
    work_operatore_logico_QD: "Operatore Logico Quesito Diagnostico"
    work_codice_metodica: "Codice Metodiche"
    work_descrizione_metodica: "Descrizione Metodica"
    work_codice_distretto: "Codice Distretto"
    work_descrizione_distretto: "Descrizione Distretto"
    work_operatore_logico_distretto: "Operatore Logico Distretto"
    work_priorita_U: "Priorità U"
    work_priorita_primo_accesso_D: "Priorità Primo Accesso D"
    work_priorita_primo_accesso_P: "Priorità Primo Accesso P"
    work_priorita_primo_accesso_B: "Priorità Primo Accesso B"
    work_accesso_programmabile_ZP: "Accesso Programmabile P"
    work_combinata: "Combinata"
    
- work_index:
    work_index_sheet: 0
    work_index_codice_QD: 30
    work_index_op_logic_distretto: 42
    work_index_codice_SISS_agenda: 11
    work_index_abilitazione_esposizione_SISS: 20
    work_index_codice_prestazione_SISS: 18
    work_index_operatore_logico_distretto: 42
    work_index_codici_disciplina_catalogo: 10
    work_index_codici_descri_disciplina_catalogo: 29
    work_index_operatore_logico_QD: 32
    work_alert_column: "BM"

- work_separator:
    work_delimiter: ","